/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

declare const self: ServiceWorkerGlobalScope & typeof globalThis;

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST, {});

// Clean up old caches
cleanupOutdatedCaches();

// Listen for skip waiting message from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Claim clients immediately after activation
self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      // Clean up old caches
      cleanupOutdatedCaches(),
      // Take control of all pages immediately
      self.clients.claim()
    ])
  );
});

// Navigate to index.html for navigation requests
const navigationRoute = new NavigationRoute(
  async ({ request }) => {
    const url = new URL(request.url);
    
    // Don't handle API routes
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/legal/')) {
      return fetch(request);
    }
    
    const cachedResponse = await caches.match('/index.html');
    return cachedResponse || fetch('/index.html');
  }
);

registerRoute(navigationRoute);

// Handle share target POST requests by converting them to GET with query params
self.addEventListener('fetch', (event: FetchEvent) => {
  const url = new URL(event.request.url);
  
  // Check if this is a share target POST request
  if (url.pathname === '/share' && event.request.method === 'POST') {
    event.respondWith(
      (async () => {
        try {
          const formData = await event.request.formData();
          const title = formData.get('title') || '';
          const text = formData.get('text') || '';
          const urlParam = formData.get('url') || '';
          const imageFile = formData.get('image') as File | null;
          
          const params = new URLSearchParams();
          if (title) params.set('title', title.toString());
          if (text) params.set('text', text.toString());
          if (urlParam) params.set('url', urlParam.toString());
          
          // For images, we could store them in IndexedDB and pass a reference
          // For now, just redirect with the text params
          if (imageFile) {
            console.log('Received shared image:', imageFile.name, imageFile.type);
            // TODO: Store image in IndexedDB and pass ID in params
          }
          
          const redirectUrl = `${url.origin}/share?${params.toString()}`;
          
          return Response.redirect(redirectUrl, 303);
        } catch (error) {
          console.error('Error handling share target:', error);
          return Response.redirect(`${url.origin}/share`, 303);
        }
      })()
    );
  }
});

export {};
